name: Java CD to K8s

on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'kubernetes/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Kubernetes kubectl
      run: kubectl -f kubernetes/sample.yml
      
