name: Java CD to K8s

on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'kubernetes/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Decrypt k8s config credentials
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output k8s_config secrets/k8s_config.gpg
      env:
        GPGPW: ${{secrets.awspassword}}
       
    - name: Kubernetes kubectl
      run: kubectl get nodes
      env: 
        KUBECONFIG: 'secrets/k8s_config'
      
