name: Propagate changes

on: [push]

jobs:
  pullrequest:
    name: Open Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Install Hub
      run: mkdir /tmp/hub && \
    (curl -SL https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-linux-amd64-${HUB_VERSION}.tgz | tar --strip 1 -zxC /tmp/hub) && \
    prefix=/usr /tmp/hub/install && \
    rm -rf /tmp/hub
    
    - name: Check version
      run: hub version
     
