name: Pull Request

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Hub
      run: mkdir /tmp/hub
      
    - run: curl -SL https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz | tar --strip 1 -zxC /tmp/hub
    - run: sudo /tmp/hub/install
    - run: rm -rf /tmp/hub
    
    - name: Check version
      run: hub version
     
